Wip/11053 direct read write on device
ChimeraTK/DeviceAccess-PythonBindings pull request #22
Opened 2023-01-31 17:38 UTC by vaeng

This PR also includes the code additions to support the device catalogue from task #7673.

2023-02-01 15:21 UTC, mhier requested changes
The changes itself look good. I have only a formal comment: The C++ code does not follow our formatting rules. Please run clang-format to fix that.

2023-02-01 15:21 UTC, mhier commented on PythonModuleMethods.h
> +  //ChimeraTK::RegisterInfo getRegister(const std::string& registerPathName);
No commented code please...

2023-02-01 21:18 UTC, vaeng commented
Good catch @mhier ! I had to re-setup clang-format. Does that look correct now?

2023-02-02 08:37 UTC, mhier approved these changes
Thanks for the reformatting. There is one comment, but I already approve to speed things up. If this TODO si for the future, please create a ticket and link to it in the source code comment.

2023-02-02 08:50 UTC, vaeng commented on deviceaccessPython.cc
> +/* TODO: Implement String and Bool Type
That is for the future and not in the scope of this feature. I have to take the time and write a conversation for the usertypes of Void, Boolean, and string. So far it does not seem like anyone is using these.

2023-02-02 09:03 UTC, merged